### ISSUE TITLE
Commands not found under MacOS 10.15.4

### ISSUE THREAD

**Issue by thgrund** [AlesTsurko/cells#4]
I am very excited about this project. Unfortunately I can't get it to run under MacOS version 10.15.4. 
For example, when I create a SuperCollider track, I get the following error in the console: 
``/bin/sh: sclang: command not found``

I have also added the path from scsynth and sclang to my PATH, as shown at https://github.com/supercollider/supercollider/blob/develop/README_MACOS.md#adding-scsynth-and-sclang-to-your-path is described. And both commands can also be executed in a terminal.

I have the same problem with a TidalCycles track: 
``/bin/sh: ghci: command not found``

**Comment by AlesTsurko** [comment]
For SuperCollider try it without scripts — add `/Applications/SuperCollider/SuperCollider.app/Contents/MacOS/` (or wherever your SC's bundle is) to `PATH`.

For TidalCycles, what does `which ghci` say?

Also, to be sure can you please check whether `PATH` is exported inside `~/.bash_profile`?

**Comment by thgrund** [comment]
Thank you very much for the answer. I was able to fix the problem. The main hint was that I should look at the ``~/.bash_profile``. 
I use zsh and in the .zshrc all paths were correctly set. I just had to export the paths for ghci and supercollider in the .bash_profile.
